### ISSUE TITLE
blastn

### ISSUE THREAD

**Issue by Wanli-HE** [leaemiliepradier/PlasForest#2]
hi!

do you know what the issue is?

Traceback (most recent call last):
  File "/home/projects/ku_00041/apps/wanli/F_pipeline/db/plasforest/PlasForest.py", line 236, in <module>
    main(sys.argv[1:])
  File "/home/projects/ku_00041/apps/wanli/F_pipeline/db/plasforest/PlasForest.py", line 114, in main
    blast_launcher(tmp_fasta, blast_table, verbose, nthreads)
  File "/home/projects/ku_00041/apps/wanli/F_pipeline/db/plasforest/PlasForest.py", line 161, in blast_launcher
    stdout, stderr = blastn_cline()
  File "/home/projects/ku_00041/apps/wanli/F_pipeline/conda_envs/ceb528a9/lib/python3.8/site-packages/Bio/Application/__init__.py", line 569, in __call__
    raise ApplicationError(return_code, str(self), stdout_str, stderr_str)

Bio.Application.ApplicationError: Non-zero return code -11 from 'blastn -out assmebly_res/SRR2145291_contigs_1kb.fasta_blast.out -outfmt 6 -query assmebly_res/SRR2145291_contigs_1kb.fasta_tmp.fasta -db plasmid_refseq.fasta -evalue 0.001 -num_threads 30'

**Comment by Wanli-HE** [comment]
here is the command line:
python3 /home/projects/ku_00041/apps/wanli/F_pipeline/db/plasforest/PlasForest.py -i assmebly_res/SRR2145342_contigs_1kb.fasta -r -b -f --threads 30 -o linear_plasmid_genome/SRR2145342_contigs_1kb.csv

**Comment by leaemiliepradier** [comment]
Blast+ tries to detect the database `plasmid_database.fasta` in the same directory from which it is launched (this is something we will change in the future). Can you try to launch PlasForest from its directory?

If it does not work:
- Are you sure Blast+ is installed on your computer?
- Blast+ takes a temporary FASTA file that is created at the beginning of PlasForest. Can you check whether it is created? In your case, it should be `assmebly_res/SRR2145291_contigs_1kb.fasta_tmp.fasta`.

**Comment by Wanli-HE** [comment]
> Blast+ tries to detect the database `plasmid_refseq.fasta` in the same directory from which it is launched (this is something we will change in the future). Can you try to launch PlasForest from its directory?
> 
> If it does not work:
> 
> * Are you sure Blast+ is installed on your computer?
> * Blast+ takes a temporary FASTA file that is created at the beginning of PlasForest. Can you check whether it is created? In your case, it should be `assmebly_res/SRR2145291_contigs_1kb.fasta_tmp.fasta`.

hi! the problem is when i  run 10 samples, 6 samples are successful, 4 are not! and the error is like above.
