### ISSUE TITLE
Test fails syntax error

### ISSUE THREAD

**Issue by Neato-Nick** [leaemiliepradier/PlasForest#3]
Running `test_plasforest.sh` errored out:

```
$ ./test_plasforest.sh 
Starting to test your PlasForest install...
Checking if all the files are here.... OK
We now run PlasForest on the test dataset...  File "PlasForest.py", line 6
SyntaxError: Non-ASCII character '\xc3' in file PlasForest.py on line 6, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
We now run PlasForest on the test dataset... ERROR
```

I'm running python 3.7.2, I get this same error whether I keep the PlasForest.py shebang as-is or change to /usr/bin/env python3

**Comment by Neato-Nick** [comment]
Interesting, running PlasForest on my data did work. It's just the test script that failed

**Comment by tazziotissot** [comment]
I advise you to still run the test script anyway. It'd be better to check whether the plasmid database has been fully downloaded.

We forgot to precise encoding in the headers of the python scripts. This is now changed in the master.
If you add "# -\*- coding: utf-8 -\*-"  at the beginning of PlasForest.py, does the issue still occur?

**Comment by Neato-Nick** [comment]
Great, it looks like the test is at least showing the database is fully downloaded. The syntax error is cleared up. Now I'm getting a new error, but I think it's a problem with my env. I think python is trying to use a py2.7 install of pickle

```
Starting to test your PlasForest install...
Checking if all the files are here.... OK
We now run PlasForest on the test dataset...~/lib/python2.7/site-pa                                                       ckages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.um                                                       ath_tests is an internal NumPy module and should not be imported. It will be rem                                                       oved in a future NumPy release.
  from numpy.core.umath_tests import inner1d
Traceback (most recent call last):
  File "PlasForest.py", line 45, in <module>
    plasforest = pickle.load(open("plasforest.sav","rb"))
  File "~/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "~/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "~/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3
We now run PlasForest on the test dataset... ERROR
``
