### ISSUE TITLE
database

### ISSUE THREAD

**Issue by zhichusun** [leaemiliepradier/PlasForest#9]
hi!

do you know what the issue is?

Traceback (most recent call last):
  File "train_plasforest.py", line 174, in <module>
    main(sys.argv[1:])
  File "train_plasforest.py", line 103, in main
    blast_launcher(inputfile, blast_table, verbose, nthreads, database)
  File "train_plasforest.py", line 126, in blast_launcher
    stdout, stderr = blastn_cline()
  File "/root/.local/lib/python3.6/site-packages/Bio/Application/__init__.py", line 574, in __call__
    raise ApplicationError(return_code, str(self), stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 2 from 'blastn -out /root/PlasForest/test.fasta_blast.out -outfmt 6 -query /root/PlasForest/test.fasta -db plasmid_refseq.fasta -evalue 0.001 -num_threads 1', message 'BLAST Database error: No alias or index file found for nucleotide database [plasmid_refseq.fasta] in search path [/root/PlasForest::]'

**Comment by zhichusun** [comment]
The plasmid database is in the same directory but it keeps showing that it cannot be found. Why? I am a beginner hope someone can help me, thank you very much.
